# Name of your site (displayed in the header)
name: Timothy Ellison

# Short bio or description (displayed in the header)
description: Web Development + Design

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: timothyjellison@live.com
  github: timothyjellison
  instagram:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

google_analytics: UA-52933192-2
url: http://www.timothyellison.com

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - gulpfile.js
