# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "blog/page:num"
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - gulpfile.js

highlighter: rouge
markdown: kramdown
google_analytics: UA-52933192-2
title: Tim Ellison

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Tim Ellison - Web Developer

description: Tim Ellison - Web Developer
author:
  name: Tim Ellison
  email: timothyellison85@gmail.com
  github: timothyjellison
  stackoverflow: 4375436
  linkedin: timothyjellison
  bio: Web Developer
  email_md5: 42bf13a66826489c4590b44e9a1f1e95

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

gems:
  - jekyll-paginate
